ALTER TABLE public.rounds
  ADD COLUMN IF NOT EXISTS game_id TEXT NOT NULL DEFAULT 'skins',
  ADD COLUMN IF NOT EXISTS game_label TEXT,
  ADD COLUMN IF NOT EXISTS custom_rules JSONB,
  ADD COLUMN IF NOT EXISTS metadata JSONB;
